# This file is part of cloudfront-log-parser.
# https://github.com/heynemann/cloudfront-log-parser

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2015, Bernardo Heynemann <heynemann@gmail.com>

language: python

python:
    - "2.7"
    - "3.4"
    - "pypy"

install:
    # install python requirements
    - make setup

script:
    # run tests
    - make test
